name: Compile and Publish LaTeX Notes

on:
  push:
    paths:
      - '**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Find changed .tex files
      - name: Find changed .tex files
        id: find_tex
        run: |
          TEX_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tex$' || true)
          echo "tex_files=$TEX_FILES" >> $GITHUB_ENV
          echo "Found .tex files: $TEX_FILES"

      # Step 3: Exit early if no .tex files were changed
      - name: Skip if no .tex files changed
        if: ${{ env.tex_files == '' }}
        run: echo "No .tex files changed. Skipping build."

      # Step 4: Compile each changed .tex file
      - name: Compile LaTeX files
        if: ${{ env.tex_files != '' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.tex_files }}
          latexmk_flavor: pdflatex

      # Step 5: Upload PDFs to GitHub Pages
      - name: Deploy PDFs to GitHub Pages
        if: ${{ env.tex_files != '' }}
        run: |
          mkdir -p out
          for tex_file in ${{ env.tex_files }}; do
            pdf_file="${tex_file%.tex}.pdf"
            mv "${pdf_file}" out/
          done
          # Copy to GitHub Pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git switch --orphan gh-pages
          git rm -rf .
          cp -r out/* .
          git add .
          git commit -m "Update PDFs"
          git push --force origin gh-pages
